<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Dapper" Version="2.1.66" />
      <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.10" />
      <PackageReference Include="prometheus-net.AspNetCore" Version="8.2.1" />
      <PackageReference Include="RabbitMQ.Client" Version="7.2.0" />
      <PackageReference Include="Serilog.AspNetCore" Version="8.0.1" />
      <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
      <PackageReference Include="Serilog.Settings.Configuration" Version="8.0.0" />
      <PackageReference Include="Serilog.Sinks.Console" Version="5.0.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DuckSharding.Shared\DuckSharding.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Properties\launchSettings.json" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="wwwroot\app.css" />
      <_ContentIncludedByDefault Remove="wwwroot\bootstrap\bootstrap.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\bootstrap\bootstrap.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\favicon.png" />
    </ItemGroup>

</Project>
